name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Init submodules
        run: git submodule update --init
      - name: Update apt...
        run: sudo apt update
      - name: Setup Python
        run: sudo apt install python3 python3-pip build-essential libssl-dev libffi-dev python3-dev && sudo pip3 install opencv-python setuptools wheel pybind11
      - name: Setup OpenCV
        run: sudo apt install libopencv-dev
      - name: Setup OpenCL
        run: sudo apt install ocl-icd-* opencl-headers
      - name: Install Pybind11
        run: cmake -S pybind11 -B pybind11/build && cmake --build pybind11/build && sudo cmake --install pybind11/build
      - name: Make Pybinding
        run: cmake -S . -B build
      - name: Build Pybindings
        run: cmake --build build --config Release
